print("Lab 1: Version Control")
print("Author: [Kazel Lunjas]")
print("Student ID: TUPM-25-0495")
print("Lab 1: Version Control")
print("Author: Kazel Lunjas")
print("Student ID: TUPM-25-0495")
print("Class Section: [BSME 1B]")
print("Login Feature Enabled")